Imports System.Data.SqlClient
Public Class FeeDataOneView
    Dim _con As SqlConnection
    ReadOnly _adapter As New SqlDataAdapter()
    Sub New()
        InitializeComponent()
        '    ' This line of code is generated by Data Source Configuration Wizard
        '    'FeeDataTableAdapter1.Fill(DataBase1.FeeData)
    End Sub


    Private Sub Fee_Data_Load(sender As Object, e As EventArgs) Handles MyBase.Load
        _con = New SqlConnection(My.Settings.FMIDATAConnectionString)
        _adapter.SelectCommand = New SqlCommand("SELECT FeeData.*,Students.Name,Students.Fname,FeeStructure.Class FROM FeeData,Students,FeeStructure where Students.[SR no]=FeeData.[SR no] AND FeeStructure.Fees_Id=FeeData.Fee_id", _con)
        Dim myTable As New DataTable
        _con.Open()
        _adapter.Fill(myTable)
        GridControl1.DataSource = myTable
        _con.Close()
    End Sub

    Private Sub SimpleButton5_Click(sender As Object, e As EventArgs) Handles SimpleButton5.Click
        If Not GridControl1.IsPrintingAvailable Then
            MessageBox.Show("The 'DevExpress.XtraPrinting' library is not found", "Error")
            Return
        End If
        ' Opens the Preview window.GridControl1.ShowPrintPreview()
    End Sub


    Private Sub ToggleSwitch1_Toggled(sender As Object, e As EventArgs) Handles ToggleSwitch1.Toggled
        If ToggleSwitch1.IsOn Then
            _adapter.SelectCommand = New SqlCommand("SELECT FeeData.*,Students.Name,Students.Fname,FeeStructure.Class FROM FeeData,Students,FeeStructure where Students.[SR no]=FeeData.[SR no] AND FeeStructure.Fees_Id=FeeData.Fee_id AND Due!=0", _con)
            Dim myTable As New DataTable
            _con.Open()
            _adapter.Fill(myTable)
            GridControl1.DataSource = myTable
            _con.Close()
        Else
            Fee_Data_Load(e, e)
        End If
    End Sub
End Class